version: '3.8'
services:
  backend:
    build:
      context: ../../
      dockerfile: infrastructure/docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
      - ../../requirements.txt:/app/requirements.txt
    environment:
      - DJANGO_SETTINGS_MODULE=hvac_ai.settings
    depends_on:
      - db
  frontend:
    build:
      context: ../../
      dockerfile: infrastructure/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/app
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hvac
      POSTGRES_USER: hvacuser
      POSTGRES_PASSWORD: hvacpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
